captcha:
  noise-count: 10
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
jwt:
  signing-key: GEA-Signing-Key
  access-expires-time: 2
  refresh-expires-time: 12
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gea
  username: root
  password: root
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: false
  log-zap: ""
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  name: "gin-element-admin"
  mode: "debug"
  port: 8888
  version: "v0.0.1"
  start_time: "2020-05-27"
  env: ""
  use-multipoint: false
zap:
  level: info
  format: console
  prefix: '[GIN-ELEMENT-ADMIN]'
  directory: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
rate-limit:
  ip-verify: true
  ip-limit-con: 10
  ip-list-key: blackListKey
  cap: 100
  quantum: 100